- spark-slave1:
    dataFolder: ''
    hdfsrole: master
    ip: 10.190.150.233
    jobhistory: 'true'
    launcher: 'true'
    restserver: 'true'
    webportal: 'true'
    yarnrole: master
    zkid: 1
    zookeeper: 'true'
- spark-slave3:
    dataFolder: ''
    hdfsrole: worker
    ip: 10.190.176.175
    yarnrole: worker
- spark-slave4:
    dataFolder: ''
    hdfsrole: worker
    ip: 10.190.177.242
    yarnrole: worker
