apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  type: NodePort
  selector:
    k8s-app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30180