machine-list:

#    - hostname: host1 # echo `hostname`
#      hostip: 192.168.1.11
#      machine-type: D8SV3
#      etcdid: etcdid1
#      sshport: PORT
#      username: username
#      password: password
#      k8s-role: master
#      dashboard: "true"
#      zkid: "1"
#      pai-master: "true"

    - hostname: spark-slave3
      hostip: 10.190.176.175
      machine-type: NC24R
      #sshport: PORT
      #username: username
      #password: password
      k8s-role: worker
      pai-worker: "true"