

spark-slave1:
    hdfsrole: master
    jobhistory: "true"
    launcher: "true"
    restserver: "true"
    yarnrole: master
    zookeeper: "true"
    zkid: 1
    ip: 10.190.150.233
    dataFolder: 
    webportal: "true"


spark-slave3:
    hdfsrole: worker
    yarnrole: worker
    dataFolder: 
    ip: 10.190.176.175


spark-slave4:
    hdfsrole: worker
    yarnrole: worker
    dataFolder: 
    ip: 10.190.177.242
